version: '3.9'
services:
  spark:
    image: docker.io/bitnami/spark:3.4
    volumes:
      - .:/opt/bitnami/spark/work
      - ./spark_conf/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties
      - ./spark_conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark-events:/tmp/spark-events
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    user: "root"
    ports:
      - '8080:8080'
      - '18080:18080'
      - '4040:4040'
    networks:
      - backend
  spark-worker:
    image: docker.io/bitnami/spark:3.4
    volumes:
      - .:/opt/bitnami/spark/work
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    user: "root"
    networks:
      - backend
  pyspark:
    image: jupyter/pyspark-notebook
    user: "root"
    environment:
      - NB_GID=100
      - GRANT_SUDO=yes
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - backend
  kafka:
    image: bitnami/kafka:3.4
    volumes:
      - ./kafka-persistence:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - backend
  cassandra:
    image: bitnami/cassandra:4.0.11
    volumes:
      - ./cassandra-persistence:/bitnami
    environment:
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
    ports:
      - "9042:9042"
    networks:
      - backend
networks:
  backend:
    driver: bridge
